# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml

  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=88]
        files: ^sdk/

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--profile, black, --line-length, "88"]
        files: ^sdk/

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=88, --extend-ignore=E203,W503]
        files: ^sdk/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]
        files: ^sdk/
        additional_dependencies: [types-all]

  - repo: local
    hooks:
      - id: go-fmt
        name: go fmt
        description: Runs gofmt on Go files
        entry: gofmt
        language: system
        args: [-w]
        files: \.go$
        pass_filenames: true

      - id: go-imports
        name: go imports
        description: Runs goimports on Go files
        entry: goimports
        language: system
        args: [-w]
        files: \.go$
        pass_filenames: true
